name: ki_badagayo
description: 기받아가요 iOS 앱
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  ios: true
  android: false
  image_path: "../icons/icon-512.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
